name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "5 22 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25

      - name: Build rule sets
        id: build
        env:
          GOAMD64: v3
        run: |
          go run -v .

      - name: Release rule sets
        if: steps.build.outputs.skip != 'true'
        run: |
          cd rule-set || exit 1
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git branch -M rule-set
          git add .
          git commit -m "${{ steps.build.outputs.tag }}"
          git push -f -u origin rule-set

      - name: Purge jsdelivr cache
        if: steps.build.outputs.skip != 'true'
        run: |
          for file in cn geolocation-!cn category-ads-all; do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@rule-set/${file}.srs"
          done
